//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u2xMainEntities1 : DbContext
    {
        public u2xMainEntities1()
            : base("name=u2xMainEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tf_pagamento> tf_pagamento { get; set; }
        public virtual DbSet<tf_tipo_movimentacao> tf_tipo_movimentacao { get; set; }
        public virtual DbSet<tf_tipo_pagamento> tf_tipo_pagamento { get; set; }
        public virtual DbSet<tf_instituicao> tf_instituicao { get; set; }
        public virtual DbSet<tf_estrelas> tf_estrelas { get; set; }
        public virtual DbSet<tf_tesouro> tf_tesouro { get; set; }
        public virtual DbSet<tf_poupanca> tf_poupanca { get; set; }
        public virtual DbSet<tf_error> tf_error { get; set; }
        public virtual DbSet<tf_investimento_RF> tf_investimento_RF { get; set; }
        public virtual DbSet<tf_investimento_RF_aporte> tf_investimento_RF_aporte { get; set; }
        public virtual DbSet<tf_investimento_RF_variacao> tf_investimento_RF_variacao { get; set; }
        public virtual DbSet<tf_usuario> tf_usuario { get; set; }
        public virtual DbSet<tf_parcela_futura> tf_parcela_futura { get; set; }
        public virtual DbSet<tf_movimentacao> tf_movimentacao { get; set; }
        public virtual DbSet<tf_movimentacao_futura> tf_movimentacao_futura { get; set; }
        public virtual DbSet<vw_email_conta_a_pagar> vw_email_conta_a_pagar { get; set; }
        public virtual DbSet<vw_email_conta_a_receber> vw_email_conta_a_receber { get; set; }
        public virtual DbSet<tf_aluno> tf_aluno { get; set; }
        public virtual DbSet<tf_mensalidade> tf_mensalidade { get; set; }
    }
}
