//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u2xMainEntities : DbContext
    {
        public u2xMainEntities()
            : base("name=u2xMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tf_instituicao> tf_instituicao { get; set; }
        public virtual DbSet<tf_movimentacao> tf_movimentacao { get; set; }
        public virtual DbSet<tf_pagamento> tf_pagamento { get; set; }
        public virtual DbSet<tf_tipo_movimentacao> tf_tipo_movimentacao { get; set; }
        public virtual DbSet<tf_usuario> tf_usuario { get; set; }
    }
}
