//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_error
    {
        public int id { get; set; }
        public string error { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public string classe { get; set; }
        public string metodo { get; set; }
    }
}
