//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_estrelas
    {
        public int id { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public bool is_processed { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tf_usuario tf_usuario { get; set; }
    }
}
