//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_investimento_RF_aporte
    {
        public Nullable<int> id_investimento_RF { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> data_compra { get; set; }
        public Nullable<decimal> valor_aporte { get; set; }
    }
}
