//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_poupanca
    {
        public int id { get; set; }
        public Nullable<System.DateTime> aporte { get; set; }
        public Nullable<decimal> rendimento { get; set; }
    }
}
