//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_parcela_futura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tf_parcela_futura()
        {
            this.tf_movimentacao = new HashSet<tf_movimentacao>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_movimentacao_futura { get; set; }
        public Nullable<System.DateTime> dt_include { get; set; }
        public Nullable<decimal> valor_real { get; set; }
        public Nullable<bool> is_pago { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_email_sent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tf_movimentacao> tf_movimentacao { get; set; }
        public virtual tf_movimentacao_futura tf_movimentacao_futura { get; set; }
    }
}
