//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_pagseguro_notification
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<bool> isProcessed { get; set; }
        public string address { get; set; }
    }
}
