//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_email_conta_a_receber
    {
        public int id { get; set; }
        public string login { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string conta { get; set; }
        public Nullable<decimal> valor_base { get; set; }
        public Nullable<System.DateTime> dt_include { get; set; }
    }
}
