//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u2x.TheFlux.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_registro
    {
        public int id { get; set; }
        public int isUsuario { get; set; }
        public string login { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isCartao { get; set; }
    }
}
